#!/usr/bin/env node
// Writes REPORT.md from every run in results/ and the labels: per repository and run, raw points (people / bots),
// candidates, verified lessons, candidates that look broken (mechanical), and precision on the labelled sample
// with a Wilson 95% interval. Precision counts the run's candidates whose every source comment is labelled.
// Usage: node scripts/learning-report/report.mjs
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { REPOS, sourceUrl, wilson } from './common.mjs';

const here = path.dirname(fileURLToPath(import.meta.url));
const read = f => JSON.parse(fs.readFileSync(path.join(here, 'results', f), 'utf8'));
const runs = fs.readdirSync(path.join(here, 'results')).filter(f => f.endsWith('.json') && f !== 'recurrence-100.json').map(read)
    .sort((a, b) => a.at.localeCompare(b.at));
const recurrence = fs.existsSync(path.join(here, 'results', 'recurrence-100.json')) ? read('recurrence-100.json') : undefined;
const labels = Object.fromEntries(REPOS.map(repo => {
    const file = path.join(here, 'labels', `${repo.replace('/', '__')}.json`);
    return [repo, fs.existsSync(file) ? JSON.parse(fs.readFileSync(file, 'utf8')).sources : {}];
}));
const pct = x => `${Math.round(x * 100)}%`;
/** A candidate as a link to its first source comment and its file: the text itself is never in the repository. */
const link = (repo, l) => `[${l.file || '(no file)'}](${sourceUrl(repo, l.prs[0], l.sources[0])})`;



const lines = ['# Learning quality on public repositories', '', 'Generated by `node scripts/learning-report/report.mjs` from `results/` and `labels/`. Method: README.md.', ''];

// Why nothing is verified, across repositories, in the latest run: the headline a change to verification must move.
const latest = runs.at(-1);
if (latest) {
    const totals = {};
    let candidates = 0, verified = 0, pairs = 0;
    for (const repo of REPOS) {
        const r = latest.repos[repo];
        if (!r?.lessons) continue;
        candidates += r.candidates;
        verified += r.verified;
        pairs += (r.nearDuplicates ?? []).length;
        for (const [k, n] of Object.entries(r.notVerified ?? {})) totals[k] = (totals[k] ?? 0) + n;
    }
    lines.push(`## Why ${verified} of ${candidates} candidates are verified (${latest.label})`, '',
        ...Object.entries(totals).sort((a, b) => b[1] - a[1]).map(([k, n]) => `- ${k}: ${n}`), '',
        'Without a person deciding, a candidate becomes a lesson only by recurrence: points on two or more pull requests by',
        'different authors, raised independently. Points join one lesson only when they are on the same file and share two',
        'identifiers on another pull request, or neither names a file and the words are the same. So a standard a team',
        `raises on different files never recurs. Candidates on different pull requests with half their words in common, any file: ${pairs}.`, '');
}
if (recurrence) {
    lines.push(`## Recurrence over ${recurrence.window} pull requests per repository (the learner's default window)`, '',
        'From the GitHub API only, no clone: a comment\'s identifiers come from its own text, not the code it points at.', '',
        '| Repository | PRs | Candidates | Lessons after merging | With identifiers | Recurring, current rule | Verified, current rule | Pairs, same person + shared identifier, any file |',
        '|---|---|---|---|---|---|---|---|');
    for (const [repo, r] of Object.entries(recurrence.repos)) lines.push(`| ${repo} | ${r.prs} | ${r.candidates} | ${r.lessons} | ${r.withIdentifiers} | ${r.currentRule.recurring} | ${r.currentRule.verified} | ${r.looserRule.pairs} (${r.looserRule.lessons} lessons) |`);
    lines.push('');
    for (const [repo, r] of Object.entries(recurrence.repos)) for (const p of r.looserRule.examples) lines.push(`- ${repo}: ${p.a} ↔ ${p.b} (shared: ${p.shared.map(x => `\`${x}\``).join(', ')})`);
    lines.push('');
}
const broken = [];
for (const repo of REPOS) {
    lines.push(`## ${repo}`, '', '| Run | PRs | Points (people / bots) | Candidates | Bot-only candidates | Verified | Looks broken | Labelled candidates | Precision (95% CI) | Not a request |', '|---|---|---|---|---|---|---|---|---|---|');
    for (const run of runs) {
        const r = run.repos[repo];
        if (!r?.lessons) continue;
        const labelled = r.lessons.filter(l => l.sources.length && l.sources.every(s => labels[repo][s]?.label));
        const asks = labelled.filter(l => l.sources.some(s => labels[repo][s].label === 'a')).length;
        const [lo, hi] = wilson(asks, labelled.length);
        const cut = r.lessons.filter(l => l.broken);
        for (const l of cut) broken.push(`- ${run.label} · ${repo} · ${link(repo, l)}`);
        lines.push(`| ${run.label} | ${r.prs} | ${r.points.total} (${r.points.people} / ${r.points.bots}) | ${r.candidates} | ${r.lessons.filter(l => l.bot).length} | ${r.verified} | ${cut.length} | ${labelled.length} | ${labelled.length ? `${pct(asks / labelled.length)} (${pct(lo)}–${pct(hi)})` : 'unlabelled'} | ${labelled.length - asks} |`);
    }
    lines.push('');
    const last = runs.at(-1)?.repos[repo];
    if (last?.lessons) {
        const why = Object.entries(last.notVerified ?? {}).sort((a, b) => b[1] - a[1]).map(([k, n]) => `${k}: ${n}`).join('; ');
        const pairs = last.nearDuplicates ?? [];
        const byId = new Map(last.lessons.map(l => [l.id, l]));
        lines.push(`Not verified in ${runs.at(-1).label}, by the first condition failed: ${why || 'none'}.`, '',
            `Clone: ${last.cloneMode}, peak ${last.cloneMb} MB, ${last.seconds} s.`, '',
            `Near-duplicate candidates on different pull requests (word overlap ≥ 0.5, any file): ${pairs.length}.`, '',
            ...pairs.slice(0, 5).map(([a, b, score]) => `- ${score} · ${link(repo, byId.get(a))} ↔ ${link(repo, byId.get(b))}`), '');
    } else if (last?.stopped) {
        lines.push(`Stopped in ${runs.at(-1).label}: ${last.stopped}`, '');
    }
}
lines.push('## Candidates that look broken (mechanical)', '', 'Starts with Or / And / But, or ends on a connector (", or", "and"). Listed for spot checks.', '', ...(broken.length ? broken : ['None.']), '');
fs.writeFileSync(path.join(here, 'REPORT.md'), lines.join('\n'));
console.log(lines.slice(0, 40).join('\n'));
