#!/usr/bin/env node
// Writes REPORT.md from every run in results/ and the labels: per repository and run, raw points (people / bots),
// candidates, verified lessons, candidates that look broken (mechanical), and precision on the labelled sample
// with a Wilson 95% interval. Precision counts the run's candidates whose every source comment is labelled. The
// held-out set (heldout/), when it has runs, is shown beside the main set's numbers.
// Usage: node scripts/learning-report/report.mjs
import fs from 'fs';
import path from 'path';
import { HELDOUT_DIR, REPOS, setPath, sourceUrl, wilson } from './common.mjs';

/** A set's runs (oldest first), its labels by repository, and its recurrence measure, read from its folder. */
function loadSet(dir) {
    const results = path.join(dir, 'results');
    const read = f => JSON.parse(fs.readFileSync(path.join(results, f), 'utf8'));
    const runs = fs.existsSync(results) ? fs.readdirSync(results).filter(f => f.endsWith('.json') && f !== 'recurrence-100.json' && !f.endsWith('.brief.json')).map(read).sort((a, b) => a.at.localeCompare(b.at)) : [];
    const repos = fs.existsSync(path.join(dir, 'prs.json')) ? Object.keys(JSON.parse(fs.readFileSync(path.join(dir, 'prs.json'), 'utf8')).prs) : [];
    const labels = Object.fromEntries(repos.map(repo => {
        const file = path.join(dir, 'labels', `${repo.replace('/', '__')}.json`);
        return [repo, fs.existsSync(file) ? JSON.parse(fs.readFileSync(file, 'utf8')).sources : {}];
    }));
    return { runs, repos, labels, recurrence: fs.existsSync(path.join(results, 'recurrence-100.json')) ? read('recurrence-100.json') : undefined };
}
const main = loadSet(setPath());
const heldout = setPath() === HELDOUT_DIR ? undefined : loadSet(HELDOUT_DIR);
const { runs, recurrence } = main;
const pct = x => `${Math.round(x * 100)}%`;

/**
 * Requests the first run had that this run lost: a request-labelled candidate of the first run none of whose
 * request sources still yields a request here (an inline comment by its id; a review body by any of the same a
 * units). Matched by source and unit, not by lesson id, so a change to the text (B2) does not count as a loss.
 */
function requestsLost(labels, repo, first, now) {
    if (!first?.lessons || !now?.lessons) return 0;
    const kept = new Set(now.lessons.filter(l => l.sources.every(s => labels[repo][s]) && isRequest(labels, repo, l))
        .flatMap(l => l.sources.flatMap(s => (l.units?.[s] ? l.units[s].map(i => `${s}#${i}`) : [s]))));
    return first.lessons.filter(l => l.sources.every(s => labels[repo][s]) && isRequest(labels, repo, l))
        .filter(l => !l.sources.some(s => (l.units?.[s] ? l.units[s].some(i => kept.has(`${s}#${i}`)) : kept.has(s)))).length;
}

/**
 * A labelled candidate is a request only if every source it came from is: an inline comment by its label, a review
 * body by the units the candidate's text came from, all of which must be a. A candidate mixing a and b units is a
 * split defect, and one whose text matches no unit cannot be credited: both count as not a request.
 */
function isRequest(labels, repo, l) {
    return l.sources.every(source => {
        const label = labels[repo][source];
        const units = l.units?.[source];
        if (label.units && units) return units.length > 0 && units.every(i => label.units[i] === 'a');
        return label.label === 'a';
    });
}
/** A candidate as a link to its first source comment and its file: the text itself is never in the repository. */
const link = (repo, l) => `[${l.file || '(no file)'}](${sourceUrl(repo, l.prs[0], l.sources[0])})`;



const lines = ['# Learning quality on public repositories', '', 'Generated by `node scripts/learning-report/report.mjs` from `results/` and `labels/`. Method: README.md.', ''];

// Why nothing is verified, across repositories, in the latest run: the headline a change to verification must move.
const latest = runs.at(-1);
if (latest) {
    const totals = {};
    let candidates = 0, verified = 0, pairs = 0;
    for (const repo of REPOS) {
        const r = latest.repos[repo];
        if (!r?.lessons) continue;
        candidates += r.candidates;
        verified += r.verified;
        pairs += (r.nearDuplicates ?? []).length;
        for (const [k, n] of Object.entries(r.notVerified ?? {})) totals[k] = (totals[k] ?? 0) + n;
    }
    lines.push(`## Why ${verified} of ${candidates} candidates are verified (${latest.label})`, '',
        ...Object.entries(totals).sort((a, b) => b[1] - a[1]).map(([k, n]) => `- ${k}: ${n}`), '',
        'Without a person deciding, a candidate becomes a lesson only by recurrence: points on two or more pull requests by',
        'different authors, raised independently. Points join one lesson only when they are on the same file and share two',
        'identifiers on another pull request, or neither names a file and the words are the same. So a standard a team',
        `raises on different files never recurs. Candidates on different pull requests with half their words in common, any file: ${pairs}.`, '');
}
if (recurrence) {
    lines.push(`## Recurrence over ${recurrence.window} pull requests per repository (the learner's default window)`, '',
        'From the GitHub API only, no clone: a comment\'s identifiers come from its own text, not the code it points at.', '',
        '| Repository | PRs | Candidates | Lessons after merging | With identifiers | Recurring, current rule | Verified, current rule | Pairs, same person + shared identifier, any file |',
        '|---|---|---|---|---|---|---|---|');
    for (const [repo, r] of Object.entries(recurrence.repos)) lines.push(`| ${repo} | ${r.prs} | ${r.candidates} | ${r.lessons} | ${r.withIdentifiers} | ${r.currentRule.recurring} | ${r.currentRule.verified} | ${r.looserRule.pairs} (${r.looserRule.lessons} lessons) |`);
    lines.push('');
    for (const [repo, r] of Object.entries(recurrence.repos)) for (const p of r.looserRule.examples) lines.push(`- ${repo}: ${p.a} ↔ ${p.b} (shared: ${p.shared.map(x => `\`${x}\``).join(', ')})`);
    lines.push('');
}
const broken = [];
const HEADER = ['| Run | PRs | Points (people / bots) | Skipped: not a request | Candidates | Bot-only candidates | Verified | Looks broken | Labelled candidates | Precision (95% CI) | Not a request | Matched no unit | Requests lost vs first run |', '|---|---|---|---|---|---|---|---|---|---|---|---|---|'];

/** One table row per run of a set for a repository; candidates that look broken are collected for spot checks. */
function runRows(set, repo) {
    const rows = [];
    for (const run of set.runs) {
        const r = run.repos[repo];
        if (!r?.lessons) continue;
        const labels = set.labels;
        const labelled = r.lessons.filter(l => l.sources.length && l.sources.every(s => labels[repo][s]?.label));
        const asks = labelled.filter(l => isRequest(labels, repo, l)).length;
        const unmatched = labelled.filter(l => Object.values(l.units ?? {}).some(u => u.length === 0)).length;
        const [lo, hi] = wilson(asks, labelled.length);
        const cut = r.lessons.filter(l => l.broken);
        for (const l of cut) broken.push(`- ${run.label} · ${repo} · ${link(repo, l)}`);
        const skippedN = Object.values(r.skipped ?? {}).reduce((n, k) => n + k, 0);
        const lost = run === set.runs[0] ? 0 : requestsLost(labels, repo, set.runs[0].repos[repo], r);
        rows.push(`| ${run.label} | ${r.prs} | ${r.points.total} (${r.points.people} / ${r.points.bots}) | ${skippedN} | ${r.candidates} | ${r.lessons.filter(l => l.bot).length} | ${r.verified} | ${cut.length} | ${labelled.length} | ${labelled.length ? `${pct(asks / labelled.length)} (${pct(lo)}–${pct(hi)})` : 'unlabelled'} | ${labelled.length - asks} | ${unmatched} | ${lost} |`);
    }
    return rows;
}

if (heldout?.runs.length) {
    lines.push('## Held out: pull requests no pattern was written against', '',
        'Merged after the main window, labelled (same rubric, same unit method) before any change was run on them. A change',
        'that only fits the main set shows here as lost requests or no gain in precision.', '',
        '**Seen since b1.** The section-aware change (b1-sections) was written after reading what B1 left here, so from',
        'b1-sections on these runs no longer count as held out. A fresh held-out sample is drawn for the last B change.', '');
    for (const repo of heldout.repos) lines.push(`### ${repo}`, '', ...HEADER, ...runRows(heldout, repo), '');
}
for (const repo of REPOS) {
    lines.push(`## ${repo}`, '', ...HEADER, ...runRows(main, repo));
    lines.push('');
    const last = runs.at(-1)?.repos[repo];
    if (last?.lessons) {
        const why = Object.entries(last.notVerified ?? {}).sort((a, b) => b[1] - a[1]).map(([k, n]) => `${k}: ${n}`).join('; ');
        const pairs = last.nearDuplicates ?? [];
        const byId = new Map(last.lessons.map(l => [l.id, l]));
        lines.push(`Not verified in ${runs.at(-1).label}, by the first condition failed: ${why || 'none'}.`, '',
            `Clone: ${last.cloneMode}, peak ${last.cloneMb} MB, ${last.seconds} s.`, '',
            `Near-duplicate candidates on different pull requests (word overlap ≥ 0.5, any file): ${pairs.length}.`, '',
            ...pairs.slice(0, 5).map(([a, b, score]) => `- ${score} · ${link(repo, byId.get(a))} ↔ ${link(repo, byId.get(b))}`), '');
    } else if (last?.stopped) {
        lines.push(`Stopped in ${runs.at(-1).label}: ${last.stopped}`, '');
    }
}
// What Phase 1's brief serves from each set's latest brief check (brief-check.mjs): counts only.
for (const [name, dir] of [['main', setPath()], ['held out', HELDOUT_DIR]]) {
    const results = path.join(dir, 'results');
    const checks = fs.existsSync(results) ? fs.readdirSync(results).filter(f => f.endsWith('.brief.json')).map(f => JSON.parse(fs.readFileSync(path.join(results, f), 'utf8'))).sort((a, b) => a.at.localeCompare(b.at)) : [];
    if (!checks.length) continue;
    lines.push(`## What the brief serves (${name} set)`, '',
        '`rigour brief --files <file>` on each repository\'s 5 files with the most candidates, serving candidates (review_lessons: all). At most 3 per file is the limit; every item should be cited and whole.', '',
        '| Check | Repository | Files | Lessons served per file | Over 3 | Uncited | Look broken |', '|---|---|---|---|---|---|---|');
    for (const check of checks) for (const [repo, r] of Object.entries(check.repos)) lines.push(`| ${check.label} | ${repo} | ${r.files} | ${r.servedPerFile.join(', ')} | ${r.overCap} | ${r.uncited} | ${r.broken} |`);
    lines.push('');
}
lines.push('## Notes', '',
    '- Run-to-run noise: immich has one point more in b1 than in baseline. It is a comment posted before the cutoff and',
    '  the merge whose commit fetch evidently failed in the baseline run (a comment on a commit that cannot be fetched is',
    '  skipped) and succeeded in b1. A change that only removes points cannot add one.',
    '- The b3 brief check for tailscale first read 1 file, 1 lesson: its lessons store was damaged by two overlapping runs',
    '  writing the same scratch store. Each run now works in its own folder; re-run alone, it reads 5 files, 3 lessons each.',
    '  Its points and candidates were counted in memory and did not change.', '');
lines.push('## Candidates that look broken (mechanical)', '', 'Starts with Or / And / But, or ends on a connector (", or", "and"). Listed for spot checks.', '', ...(broken.length ? broken : ['None.']), '');
fs.writeFileSync(setPath('REPORT.md'), lines.join('\n'));
console.log(lines.slice(0, 40).join('\n'));
