import fs from 'fs';
import os from 'os';
import path from 'path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { isGeneratedFile, withoutGenerated } from './generated-files.js';

let dir: string;
beforeEach(() => { dir = fs.mkdtempSync(path.join(os.tmpdir(), 'generated-')); });
afterEach(() => { fs.rmSync(dir, { recursive: true, force: true }); });

describe('generated files', () => {
    it('recognises generated files by name and by the marker at their top', () => {
        fs.writeFileSync(path.join(dir, 'client.ts'), '// This file is auto-generated by @hey-api/openapi-ts\nexport const x = 1;\n');
        fs.writeFileSync(path.join(dir, 'schema.ts'), '/* eslint-disable */\n// @generated by protoc\n');
        fs.writeFileSync(path.join(dir, 'handwritten.ts'), "// Generates the client; edit freely.\nexport const generate = () => 'x';\n");
        expect(isGeneratedFile(dir, 'client.ts')).toBe(true);
        expect(isGeneratedFile(dir, 'schema.ts')).toBe(true);
        expect(isGeneratedFile(dir, 'src/api/client.gen.ts')).toBe(true);
        expect(isGeneratedFile(dir, 'src/__generated__/types.ts')).toBe(true);
        expect(isGeneratedFile(dir, 'handwritten.ts')).toBe(false);
        expect(isGeneratedFile(dir, 'src/missing.ts')).toBe(false);
    });

    it('drops generated files from the change under review', () => {
        const changed = { 'src/a.ts': new Set([1]), 'src/b.gen.ts': new Set([2]) };
        expect(Object.keys(withoutGenerated(dir, changed))).toEqual(['src/a.ts']);
    });
});
