import type { Config } from '../types/index.js';

export const UNIVERSAL_CONFIG: Config = {
    commands: {},
    gates: {
        max_file_lines: 500,
        forbid_todos: true,
        forbid_fixme: true,
        required_files: ['docs/SPEC.md', 'docs/ARCH.md', 'docs/DECISIONS.md', 'docs/TASKS.md'],
        ast: {
            complexity: 10,
            max_methods: 10,
            max_params: 5,
        },
        dependencies: {
            forbid: [],
            detect_unused: true,
            detect_heavy_alternatives: true,
            detect_duplicate_purpose: true,
            unused_allowlist: [],
        },
        architecture: {
            boundaries: [],
        },
        safety: {
            max_files_changed_per_cycle: 10,
            protected_paths: ['.github/**', 'docs/**', 'rigour.yml'],
        },
        context: {
            enabled: true,
            sensitivity: 0.8,
            mining_depth: 100,
        },
        environment: {
            enabled: true,
            enforce_contracts: true,
            tools: {},
            required_env: [],
        },
        retry_loop_breaker: {
            enabled: true,
            max_retries: 3,
            doc_sources: {},
        },
        agent_team: {
            enabled: false,
            max_concurrent_agents: 3,
            task_ownership: 'strict',
        },
        checkpoint: {
            enabled: false,
            interval_minutes: 15,
            quality_threshold: 80,
            drift_detection: true,
        },
        security: {
            enabled: true,
            sql_injection: true,
            xss: true,
            path_traversal: true,
            hardcoded_secrets: true,
            insecure_randomness: true,
            command_injection: true,
            block_on_severity: 'high',
            block: false,
        },
        frontend_secret_exposure: {
            enabled: true,
            block_on_severity: 'high',
            check_process_env: true,
            check_import_meta_env: true,
            secret_env_name_patterns: [
                '(?:^|_)(?:secret|private)(?:_|$)',
                '(?:^|_)(?:token|api[_-]?key|access[_-]?key|client[_-]?secret|signing|webhook)(?:_|$)',
                '(?:^|_)(?:db[_-]?url|database[_-]?url|connection[_-]?string)(?:_|$)',
            ],
            safe_public_prefixes: ['NEXT_PUBLIC_', 'VITE_', 'PUBLIC_', 'NUXT_PUBLIC_', 'REACT_APP_'],
            frontend_path_patterns: [
                '(^|/)pages/(?!api/)',
                '(^|/)components/',
                '(^|/)src/components/',
                '(^|/)src/views/',
                '(^|/)src/app/',
                '(^|/)app/(?!api/)',
                '(^|/)views/',
                '(^|/)public/',
            ],
            server_path_patterns: [
                '(^|/)pages/api/',
                '(^|/)src/pages/api/',
                '(^|/)app/api/',
                '(^|/)src/app/api/',
                '\\.server\\.(?:ts|tsx|js|jsx|mjs|cjs)$',
            ],
            allowlist_env_names: [],
        },
        staleness: {
            enabled: false,
            rules: {
                'no-var': true,
                'no-commonjs': false,
                'no-arguments': false,
                'prefer-arrow': false,
                'prefer-template': false,
                'prefer-spread': false,
                'prefer-rest': false,
                'prefer-const': false,
            },
        },
        duplication_drift: {
            enabled: true,
            similarity_threshold: 0.8,
            min_body_lines: 5,
        },
        hallucinated_imports: {
            enabled: true,
            ignore_patterns: [
                '\\.css$', '\\.scss$', '\\.less$', '\\.svg$', '\\.png$', '\\.jpg$',
                '\\.json$', '\\.wasm$', '\\.graphql$', '\\.gql$',
            ],
        },
        inconsistent_error_handling: {
            enabled: true,
            max_strategies_per_type: 2,
            min_occurrences: 3,
            ignore_empty_catches: false,
        },
        context_window_artifacts: {
            enabled: true,
            min_file_lines: 180,
            degradation_threshold: 0.55,
            signals_required: 4,
        },
        promise_safety: {
            enabled: true,
            check_unhandled_then: true,
            check_unsafe_parse: false,
            check_async_without_await: true,
            check_unsafe_fetch: true,
            ignore_patterns: [],
        },
        phantom_apis: {
            enabled: true,
            check_node: true,
            check_python: true,
            check_go: true,
            check_csharp: true,
            check_java: true,
            ignore_patterns: [],
        },
        deprecated_apis: {
            enabled: true,
            check_node: true,
            check_python: true,
            check_web: true,
            check_go: true,
            check_csharp: true,
            check_java: true,
            block_security_deprecated: false,
            ignore_patterns: [],
        },
        test_quality: {
            enabled: true,
            check_empty_tests: true,
            check_tautological: true,
            check_mock_heavy: true,
            check_assertion_free_async: true,
            max_mocks_per_test: 5,
        },
        governance: {
            enabled: true,
            enforce_memory: false,
            enforce_skills: false,
            block_native_memory: true,
            protected_memory_paths: [
                'CLAUDE.md', '.claude/CLAUDE.md',
                '.clinerules', '.clinerules/**',
                '.windsurf/memories/**',
                '.github/copilot-instructions.md',
            ],
            protected_skills_paths: [
                '.claude/skills/**', '.claude/rules/**', '.claude/commands/**',
                '.cursorrules', '.cursor/rules/**', '.cursor/prompts/**',
                '.cline/rules/**',
                '.windsurf/rules/**', '.windsurfrules',
                '.github/instructions/**', 'copilot-instructions.md',
            ],
            exempt_paths: [
                '.claude/settings.json',
                '.cursor/hooks.json',
                '.windsurf/hooks.json',
            ],
        },
        style_drift: {
            enabled: true,
            deviation_threshold: 0.25,
            sample_size: 100,
            baseline_path: '.rigour/style-baseline.json',
        },
        logic_drift: {
            enabled: true,
            baseline_path: '.rigour/logic-baseline.json',
            track_operators: true,
            track_branches: false,
            track_returns: false,
        },
        unindexed_reads: {
            enabled: false,
            migrations: [],
        },
        deprecated_dependencies: {
            enabled: false,
        },
        unused_exports: {
            enabled: true,
            allow: [],
            block: false,
        },
        orphan_files: {
            enabled: true,
            allow: [],
            block: false,
        },
        compiled_lessons: {
            enabled: true,
            block: false,
        },
        query_patterns: {
            enabled: true,
            block: false,
        },
        optional_params: {
            enabled: true,
        },
        change_sweep: {
            enabled: true,
            block: false,
        },
        redundancy: {
            enabled: true,
            wire_contracts: [],
            schema_migrations: ['supabase/migrations'],
        },
        duplicate_functions: {
            enabled: true,
            block: false,
        },
        migration_order: {
            enabled: false,
            dirs: ['**/supabase/migrations'],
        },
        semantic_bugs: {
            enabled: true,
        },
        side_effect_analysis: {
            enabled: true,
            check_unbounded_timers: true,
            check_unbounded_loops: true,
            check_process_lifecycle: true,
            check_recursive_depth: true,
            check_resource_lifecycle: true,
            check_retry_without_limit: true,
            check_circular_triggers: true,
            check_auto_restart: true,
            block: false,
            ignore_patterns: [],
        },
        deep: {
            temperature: 0.1,
            intent_checks: false,
            checks: {
                solid: true,
                dry: true,
                design_patterns: true,
                language_idioms: true,
                error_handling: true,
                test_quality: true,
                architecture: true,
                code_smells: true,
            },
        },
    },
    hooks: {
        require_review_ack: false,
    },
    output: {
        report_path: 'rigour-report.json',
    },
    brief: {
        enabled: true,
        max_items: 10,
    },
    learning: {
        outcomes: { mode: 'off', window_days: 30, demote_after: 2 },
    },
    review: {
        include_heuristics: false,
        show_preexisting: false,
        coverage: true,
        review_points: true,
        goal: 'off',
        reviewer: {
            enabled: false,
            on_push: 'background',
            reviewers: ['claude'],
            mode: 'single',
            models: {},
            timeout_ms: 900000,
            panel: 'off',
            mode_required: false,
            panel_max_items: 20,
            dismissals: false,
            orchestrator: 'off',
            judges: 2,
            escalate: 'always',
            cross_models: {},
            tiers: { cheap: {} },
            judge_env: {},
            reasoning: {},
        },
    },
    ignore: [],
};
